from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

from pymilvus.model.sparse import BM25EmbeddingFunction
from pymilvus.model.sparse.bm25.tokenizers import build_default_analyzer
from scipy.sparse import csr_matrix, load_npz

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.drg_pipeline import compute_bm25_scores, top_k_score_indices


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Query local BM25 model directly")
    parser.add_argument("--keyword", required=True, help="Keyword for retrieval")
    parser.add_argument("--top-k", type=int, default=10, help="Top K results")
    parser.add_argument(
        "--artifact-dir",
        type=Path,
        default=Path("artifacts/local_bm25"),
        help="Directory generated by train_bm25_local.py",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    model_path = args.artifact_dir / "bm25_model.json"
    records_path = args.artifact_dir / "records.json"
    matrix_path = args.artifact_dir / "doc_vectors.npz"

    if not model_path.exists() or not records_path.exists() or not matrix_path.exists():
        raise FileNotFoundError(
            f"Missing artifacts in {args.artifact_dir}. Run scripts/train_bm25_local.py first."
        )

    records = json.loads(records_path.read_text(encoding="utf-8"))
    doc_vectors = csr_matrix(load_npz(matrix_path))

    analyzer = build_default_analyzer(language="zh")
    bm25 = BM25EmbeddingFunction(analyzer=analyzer)
    bm25.load(str(model_path))

    query_vector = csr_matrix(bm25.encode_queries([args.keyword]))
    scores = compute_bm25_scores(doc_vectors, query_vector)

    ranked_indices = top_k_score_indices(scores, args.top_k)
    results = []
    for rank, idx in enumerate(ranked_indices, start=1):
        if float(scores[idx]) <= 0:
            continue
        item = records[idx]
        results.append(
            {
                "rank": rank,
                "score": float(scores[idx]),
                "drg_name": item.get("drg_name"),
                "start_cost_cny": item.get("start_cost"),
                "cap_cost_cny": item.get("cap_cost"),
            }
        )

    if not results:
        fallback = [r for r in records if args.keyword in str(r.get("drg_name", ""))][: args.top_k]
        results = [
            {
                "rank": idx,
                "score": 0.0,
                "drg_name": item.get("drg_name"),
                "start_cost_cny": item.get("start_cost"),
                "cap_cost_cny": item.get("cap_cost"),
            }
            for idx, item in enumerate(fallback, start=1)
        ]

    print(json.dumps(results, ensure_ascii=False, indent=2))


if __name__ == "__main__":
    main()

